DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS solving_expression;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE solving_expression (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expression TEXT NOT NULL,
  solving TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
